### ISSUE TITLE
Errors in annotator on windows

### ISSUE THREAD

**Issue by Alex-Karmazin** [KarchinLab/open-cravat-modules-karchinlab#9]
While implementing tutorial for annotator on windows 10 faced error.  Execution of annotator with next command cause error:

(openCravatPlugin) C:\dev\python\openCravatPlugin>oc run input.vcf -a example -l hg38
Input file(s): C:\dev\python\openCravatPlugin\input.vcf
Genome assembly: hg38
Running converter...
        Converter (converter)           Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_class.py", line 515, in main
    self.run_converter()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_class.py", line 1230, in run_converter
    self.numinput, self.converter_format = converter.run()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_convert.py", line 419, in run
    converter.setup(f)
  File "C:\dev\python\openCravatPlugin\modules\converters\vcf-converter\vcf-converter.py", line 60, in setup
    import vcf
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\vcf\__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (unknown location)

Finished with an exception. Runtime: 0.892s
Check C:\dev\python\openCravatPlugin\input.vcf.log

After examine __init__.py I found that imports are shadowed with system modules. To import files from same folder should be used dot before name. This error disappears when I modified file as:
...
from .parser import Reader, Writer
from .parser import VCFReader, VCFWriter
from .filters import Base as Filter
from .parser import RESERVED_INFO, RESERVED_FORMAT
...

But after solving this error new one appears:

(openCravatPlugin) C:\dev\python\openCravatPlugin>oc run input.vcf -a example -l hg38
Input file(s): C:\dev\python\openCravatPlugin\input.vcf
Genome assembly: hg38
Running converter...
        Converter (converter)           Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_class.py", line 515, in main
    self.run_converter()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_class.py", line 1230, in run_converter
    self.numinput, self.converter_format = converter.run()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\cravat\cravat_convert.py", line 419, in run
    converter.setup(f)
  File "C:\dev\python\openCravatPlugin\modules\converters\vcf-converter\vcf-converter.py", line 61, in setup
    reader = vcf.Reader(f, compressed=False)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\vcf\parser.py", line 490, in __init__
    self._parse_metainfo()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\vcf\parser.py", line 505, in _parse_metainfo
    line = self.reader.next()
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'

Finished with an exception. Runtime: 0.791s
Check C:\dev\python\openCravatPlugin\input.vcf.log

The same code running on Linux without any problems. On Windows I use anaconda as python environment with python version 3.9
GUI runs without any problem on Windows too.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin the issue is due to the conflict between `pyvcf` and the latest `setuptools`, which causes an old version of `pyvcf` to be installed with `setuptools` version >= 58. Please try the following and let me know if it works.
```
>pip install "setuptools<58" --upgrade
>pip uninstall pyvcf
>pip install pyvcf
```

**Comment by Alex-Karmazin** [comment]
Thank you, it solve all the errors.
